spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  application:
    name: gateway-service
  profiles:
    active: dev
  main:
    web-application-type: reactive
    allow-circular-references: true

