server:
  port: 8082

spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tamerlan-Aghayev/config-files.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

